versions:
  "11.0.1":
    folder: all
  "11.0.0":
    folder: all
  "10.0.3":
    folder: all
  "10.0.2":
    folder: all
  "10.0.1":
    folder: all
  "10.0.0":
    folder: all
  "9.5.2":
    folder: all
